#ifndef DATA_CENTER_TASK_COMMON_H
#define DATA_CENTER_TASK_COMMON_H

#define DATA_CENTER_TASK_CORE_ID 0
#define DATA_CENTER_TASK_PRIORITY 5
#define DATA_CENTER_TASK_STACK_SIZE 1024 * 2

#define DATA_CENTER_SEND_PERIOD_MS 1000



#endif