#ifndef SEED_PLANTER_TASK_COMMON_H
#define SEED_PLANTER_TASK_COMMON_H

#define SEED_PLANTER_STACK_SIZE                   4096
#define SEED_PLANTER_TASK_PRIORITY                4
#define SEED_PLANTER_CORE_ID                      0

// TODO: FIX SEEDER PARAMETERS
#define SEED_PLANTER_CUTTER_DISC_ENCODER_A        10
#define SEED_PLANTER_CUTTER_DISC_ENCODER_B        11
#define SEED_PLANTER_CUTTER_DISC_PWMA             12
#define SEED_PLANTER_CUTTER_DISC_PWMB             13

#define SEED_PLANTER_SEED_DISPENSER_ENCODER_A     14
#define SEED_PLANTER_SEED_DISPENSER_ENCODER_B     15
#define SEED_PLANTER_SEED_DISPENSER_PWMA          16
#define SEED_PLANTER_SEED_DISPENSER_PWMB          17

#define SEED_PLANTER_CUTTER_DISC_KP               10
#define SEED_PLANTER_CUTTER_DISC_KI               11
#define SEED_PLANTER_CUTTER_DISC_KD               12

#define SEED_PLANTER_SEED_DISPENSER_KP            10
#define SEED_PLANTER_SEED_DISPENSER_KI            11
#define SEED_PLANTER_SEED_DISPENSER_KD            12

#define SEED_PLANTER_BDC_ENCODER_PCNT_HIGH_LIMIT  1000
#define SEED_PLANTER_BDC_ENCODER_PCNT_LOW_LIMIT   -1000
#define SEED_PLANTER_MCPWM_GROUP                    1
#define SEED_PLANTER_PID_LOOP_PERIDO_MS           10


#define SEED_PLANTER_MOTORS_PWM_FREQ              10000








#endif
