#ifndef NAVIGATION_TASK_COMMON_H
#define NAVIGATION_TASK_COMMON_H

#define NAVIGATION_TASK_STACK_SIZE      9046
#define NAVIGATION_TASK_CORE_ID         0
#define NAVIGATION_TASK_PRIORITY        8

#endif
