#ifndef STATE_MACHINE_TASK_COMMON_H
#define STATE_MACHINE_TASK_COMMON_H

#define STATE_MACHINE_TASK_STACK_SIZE 2048
#define STATE_MACHINE_TASK_PRIORITY 20
#define STATE_MACHINE_TASK_CORE_ID 0


#endif