#ifndef STATE_MACHINE_TASK_COMMON_H
#define STATE_MACHINE_TASK_COMMON_H

#define STATE_MACHINE_TASK_STACK_SIZE 2048
#define STATE_MACHINE_TASK_PRIORITY 10
#define STATE_MACHINE_TASK_CORE_ID 1


#endif