#ifndef TASKS_COMMON_H
#define TASKS_COMMON_H

// Right motor connected to Driver's OUT2

#define TRACTION_CONTROL_STACK_SIZE         4096
#define TRACTION_CONTROL_TASK_PRIORITY      12 
#define TRACTION_CONTROL_CORE_ID            0

#define BDC_MCPWM_TIMER_RESOLUTION_HZ       10000000 // 10MHz, 1 tick = 0.1us
#define BDC_ENCODER_PCNT_HIGH_LIMIT         2000
#define BDC_ENCODER_PCNT_LOW_LIMIT          -2000
#define BDC_PID_LOOP_PERIOD_MS              10

#define TRACTION_MOTORS_MCPWM_GROUP         0
#define TRACTION_MOTORS_PWM_FREQ            20000       // 25kHz PWM

#define TRACTION_MOTOR_LEFT_PWMA            27
#define TRACTION_MOTOR_LEFT_PWMB            14
#define TRACTION_MOTOR_LEFT_ENCODER_A       26
#define TRACTION_MOTOR_LEFT_ENCODER_B       25

#define TRACTION_MOTOR_RIGHT_PWMA           33
#define TRACTION_MOTOR_RIGHT_PWMB           32
#define TRACTION_MOTOR_RIGHT_ENCODER_A      34
#define TRACTION_MOTOR_RIGHT_ENCODER_B      35

#define MOTOR1_ENCODER_RES                  908
#define MOTOR2_ENCODER_RES                  908

#define TRACTION_MOTOR_LEFT_KP              0.65f
#define TRACTION_MOTOR_LEFT_KI              0.54f
#define TRACTION_MOTOR_LEFT_KD              0.5f

//#define TRACTION_MOTOR_LEFT_KP              0.007859181f
//#define TRACTION_MOTOR_LEFT_KI              3.785918094f
//#define TRACTION_MOTOR_LEFT_KD              0.0000001f
#define TRACTION_MOTOR_RIGHT_KP             0.65f
#define TRACTION_MOTOR_RIGHT_KI             0.54f
#define TRACTION_MOTOR_RIGHT_KD             0.5f

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

#define TRACTION_MOTOR_MAX_PULSES           550
#define TRACTION_MOTOR_MAX_REVS             2.718f

// Fix loosy conversions 
#define TRACTION_PULSES_PER_REV_10MS        204.0f 
#define TRACITON_TOTAL_PULSES_PER_REV       TRACTION_PULSES_PER_REV_10MS * 100.0f 

#define TRACTION_PULSES2REV_FACTOR          1/TRACTION_PULSES_PER_REV_10MS

// One revolution has 2040 pulses = 2*PI rad
#define TRACTION_PULSES2RAD_FACTOR          (2 * M_PI) / (TRACITON_TOTAL_PULSES_PER_REV)

#define TRACTION_CONV_REV2PULSES(X)         (X * TRACTION_PULSES_PER_REV_10MS)
#define TRACTION_CONV_PULSES2REV(X)         (X * TRACTION_PULSES2REV_FACTOR)
#define TRACTION_CONV_PULSES2RAD(X)         (X * TRACTION_PULSES2RAD_FACTOR)
#endif