#ifndef KALMAN_FILTER_TASK_COMMON_H
#define KALMAN_FILTER_TASK_COMMON_H

#define KALMAN_FILTER_STACK_SIZE            4096
#define KALMAN_FILTER_CORE_ID               0
#define KALMAN_FILTER_TASK_PRIORITY         12 

#endif