#ifndef WAYPOINT_CONTROLLER_TASK_COMMON_H
#define WAYPOINT_CONTROLLER_TASK_COMMON_H

#define WAYPOINT_CONTROLLER_STACK_SIZE      9046
#define WAYPOINT_CONTROLLER_CORE_ID         0
#define WAYPOINT_CONTROLLER_PRIORITY        8

#endif
